### PR TITLE
Fixed initialize InfluxDB in Ruby 3.0

### LINKED ISSUE #12: support ruby 3.0.1
We updated ruby and pick up bugs
```
wrong number of arguments (given 1, expected 0; required keyword: influxdb_client)
```

it broke our stagings because all the tasks hit

we had to disable the library in our project

### PR DESCRIPTION
**Pull request by StoneGod**

### CODE REVIEW

**Review by tuwilof — APPROVED** [review]
💪

**Comment by vassilevsky** [comment]
I haven't seen a single failure. How did it even fail?

**Comment by vassilevsky** [comment]
The title says "Ruby 3" but there is no Ruby 3 addition in the files?

**Comment by StoneGod** [comment]
> I haven't seen a single failure. How did it even fail?
It failed like this
```
2021-04-20T15:50:01.685640+04:00 Job EE5A0xXR WARN - PID:27719 NameError: undefined local variable or method `influxdb_client' for #<Sidekiq::Middleware::Server::InfluxDB:0x00007fdcf2ac8ee8>
2021-04-20T15:50:01.685731+04:00 Job EE5A0xXR WARN - PID:27719 /Users/stonegod/my_projects/sidekiq-influxdb/lib/sidekiq/middleware/server/influxdb.rb:12:in `initialize' /Users/stonegod/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:156:in `new'
```

**Comment by StoneGod** [comment]
Problem in method `def add` https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/chain.rb#L92

**Comment by vassilevsky** [comment]
Released **v1.4.1**.

**Pull request merged**
